# Generated by Django 5.2 on 2025-06-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0003_content_delete_audio_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
    ]
